### PR TITLE
Implement math.ceil stdlib method

### PR DESCRIPTION
**Pull request by c-wiren**
Implements the `math.ceil` method from Python's standard library.
Tested on Python 3.9.4 with Java OpenJDK 1.8.0_302.

### CODE REVIEW

**Review by sebbersk — COMMENTED** [review]
Before reviewing further, we were wondering why you chose to add/implement the `__ceil__` function inside the type classes (`Float`, `Int`) as it is not an [operator](https://docs.python.org/3/library/operator.html) in Python but a method of the math module.

**Comment by c-wiren** [comment]
If you try `__ceil__` on a float in python it works. In that way you can override `__ceil__` for any class and use math.ceil on it, and with this implementation, it works just like Python. Though I see that it is not included in the operators, do you know another way to achieve the same outcome?
[object.\_\_ceil\_\_](https://docs.python.org/3/reference/datamodel.html#object.__ceil__)

**Comment by sebbersk** [comment]
> If you try `__ceil__` on a float in python it works. In that way you can override `__ceil__` for any class and use math.ceil on it, and with this implementation, it works just like Python. Though I see that it is not included in the operators, do you know another way to achieve the same outcome?

Ah! I did not try that :) I think you could get the same outcome by doing something similar to what you have in your `Float.java` file and putting it in the `math.java` file. Feel free to look at our implementation of the `isqrt()`-method to see how we approached the issue :) .

**Comment by pottu** [comment]
Indeed, it seems we overlooked that only operators were to be present as those types of methods.

While we're on the subject, just curious to what your view is on the fact that the [documentation](https://docs.python.org/3.9/library/math.html#math.ceil) specifies that only non-floats (for reasons unclear to me) be delegated to `__ceil__()` as opposed to any number type. I raise this point as I believe you delegate floats aswell. Is this an active decision (as again, I cannot see the reason for not delegating always)?

**Comment by c-wiren** [comment]
The documentation seems unclear on that point, though since using `__ceil__()` on a float is possible, we wanted to mimic the behavior of Python as closely as possible. Please check the updated code, it should make more sense.

**Comment by pottu** [comment]
Okay, you seem to have a justified reason for how `math.ceil` has been implemented. After all, the importance is that the function remains functionally equivalent and not necessarily implementation-wise equivalent. Glad to hear your views on things, though. We'll ongo to review the code in its current stance.

**Review by pottu — CHANGES_REQUESTED** [review]
I have looked over your code, and run stylechecks and tests. It looks good to me!
The only thing I picked up on is that the exception message given when `math.ceil` is used with a bad type is _slightly_ off. This (non-passing) test case captures the behaviour:
```
    def test_ceil_exception_msg(self):
        self.assertCodeExecution("""
        import math
        try:
            math.ceil("str")
        except Exception as e:
            print(e)
        """)
```
This might have been changed with a newer version of Python (I used 3.8.0) -- if so, I am unsure what the best resolution is.

**Comment by c-wiren** [comment]
That is true! Small difference :)
Though it made me find another problem, if I run `("str").__ceil__()` it will give me a TypeError instead of AttributeError. Both issues are fixed now!

**Review by sebbersk — APPROVED** [review]
I have run the style checks and tests. Everything looks fine to me :) Well done

**Review by pottu — APPROVED** [review]

**Pull request merged**
