### PR TITLE
Partial Implementation of Datetime.datetime

### PR DESCRIPTION
**Pull request by itzsandeepsunny**
Provides a partial implementation of Python's datetime.datetime.

Includes the following:
```

- Comparison Methods
- fromordinal
- isoweekday

```

### CODE REVIEW

**Review by pottu — CHANGES_REQUESTED** [review]
Here are my notes:
1. Some `__doc__`s seem off, e.g.
```
python3.8> datetime.datetime.date.__doc__
'Return date object with same year, month and day.'
```
2. I couldn't find tests for `max` and `min` (albeit they get coverage due to initialization in other tests).
3. Test for `today` lacks assertions on the returned object.
4. A bit unsure of their usage, but methods `__year__` and friends should probably be declared private, or perhaps removed altogether since `year` and friends are public?

**Comment by c-wiren** [comment]
Looks good! The exception messages seem to be correct, and you've got an impressive line coverage with the tests. There is some strange usage of doubles in the code, though it was there from the start.

**Comment by sebbersk** [comment]
> Here are my notes:
> 
> 1. Some `__doc__`s seem off, e.g.
> 
> ```
> python3.8> datetime.datetime.date.__doc__
> 'Return date object with same year, month and day.'
> ```
> 
> 1. I couldn't find tests for `max` and `min` (albeit they get coverage due to initialization in other tests).
> 2. Test for `today` lacks assertions on the returned object.
> 3. A bit unsure of their usage, but methods `__year__` and friends should probably be declared private, or perhaps removed altogether since `year` and friends are public?

Hi! Thank you for your comment. We fixed the `__doc__`s  and created tests for `min` and `max`. For today it was a little difficult for us. As we need to consider seconds and  microseconds as well so we tested only for years day and month. If you have some ideas of how it could be done please let us know :). For `__year__` and friends we decided to make the private.

**Review by c-wiren — APPROVED** [review]

**Comment by c-wiren** [comment]
What you could do if you want to test seconds as well is to create an expected date before and after using `today()` and  make sure the result is in that range.

**Comment by pottu** [comment]
> For today it was a little difficult for us. As we need to consider seconds and microseconds as well so we tested only for years day and month. If you have some ideas of how it could be done please let us know :).

That handn't entered my mind.. But I like @c-wiren's approach. Otherwise, testing for date is better than nothing.

While on the subject, it just entered my mind that if you run the test suite close to midnight, there is a slight chance of tests failing due to a new day beginning (right?).. A solution for all these problems (then also existent in #3) might be to use a mock, but we can leave that for the future as a separate addition.

**Review by pottu — APPROVED** [review]

**Pull request merged**
